name: build-and-test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel
          pip install -r build_tools/requirements.txt
      - name: Build wheel
        run: python setup.py sdist bdist_wheel
      - name: Install from wheel
        run: pip install --pre --no-index --no-deps --find-links dist/ sktime
      - name: Run examples
        run: build_tools/run_examples.sh
        shell: bash
